user:
  run_dir: ./output/pendulum_output/${now:%Y-%m-%d}/${now:%H-%M-%S}
  wandb_enabled: false
  wandb_entity: ???
  load_lyaloss: null
  Vmin_x_pgd_path: null
  derivative_x_buffer_path: null
wandb_name: pendulum_output
approximate_lqr: false
pgd_verifier_steps: 300
model:
  lyapunov:
    quadratic: true
    hidden_widths:
    - 16
    - 16
    - 8
  load_lyaloss: null
  kappa: 0.1
  V_decrease_within_roa: false
  limit_scale: 0.1
  V_psd_form: L1
  rho_multiplier:
  - 2.0
  - 1.8
  - 1.6
  - 1.4
  u_max: 0.25
  save_lyaloss: true
train:
  train_lyaloss: false
  Vmin_x_pgd_path: null
  hard_max: true
  num_samples_per_boundary: 1024
  learning_rate: 0.001
  lr_controller: 0.001
  batch_size: 100
  epochs: 40
  pgd_steps: 50
  Vmin_x_pgd_buffer_size: 500000
  buffer_size: 10000
  samples_per_iter: 100
  max_iter: 100
  derivative_x_buffer_path: null
  lr_scheduler: false
  wandb:
    enabled: ${user.wandb_enabled}
    project: neural_lyapunov_training
    name: ${now:%Y.%m.%d-%H.%M.%S}_${wandb_name}
    dir: ${user.run_dir}
    entity: ${user.wandb_entity}
  update_Vmin_boundary_per_epoch: false
loss:
  candidate_scale: 0.6
  candidate_roa_states_weight: 0
  l1_reg: 0.001
  observer_ratio:
  - 0.0001
  - 0.0001
  - 1.0e-05
  - 1.0e-05
  always_candidate_roa_regulizer: true
  ibp_ratio_derivative: 0
  sample_ratio_derivative: 1
  ibp_ratio_positivity: 0
  sample_ratio_positivity: 0
  Vmin_x_boundary_weight: 0
  Vmax_x_boundary_weight: 0
seed: 1234
